### ISSUE TITLE
Become a Verified Creator action

### ISSUE THREAD

**Issue by bruno-garcia** [NuGet/setup-nuget#24]
Actions can be verified [such as](https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby):

![image](https://user-images.githubusercontent.com/1633368/103956825-4e054d00-5117-11eb-8847-78f31fc25ab7.png)

This helps with trust given that workflows often have secrets in them.

GH docs on the matter:

https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/finding-and-customizing-actions

**Comment by bruno-garcia** [comment]
Oh, further research and I found:

> Currently, there is no way to request verification. Creators are verified because they have an existing relationship GitHub, and GitHub has worked closely with the creator to create their actions. We are continuing to evaluate this process, and we may open it up more broadly in the future.

That's from June 2020, not sure if still relevant.

**Comment by ismaelhamed** [comment]
Looks like there's now a process in place to apply for verification: https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization

**Comment by kenta2097** [comment]
I’m writing regarding the GH Action [Setup NuGet.exe for use with actions](https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions)

Our project is starting to migrate the CI/CD to GH Actions and we are interested to use your Actions.
Providing some context, our Global Security team requires the "Creator Verified by GitHub" badge to start the internal GHA verification process, due to this we are blocked to use unverified Actions.

We would be grateful if you could start the GH Action verification process, as it would help us greatly.

I believe it must improve your impact in the whole GitHub community as a partner organization and also, you are letting us use your actions.

You can find more helpful information in the following articles from GitHub Docs as a good starting point on the process.

[Applying for publisher verification for your organization](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/applying-for-publisher-verification-for-your-organization)
[About marketplace badges](https://docs.github.com/en/developers/github-marketplace/github-marketplace-overview/about-marketplace-badges)

**Comment by kenta2097** [comment]
Hi @jeffkl 


As talked by email the [.NET command-line interface](https://eur02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fnuget%2Freference%2Fdotnet-commands%23package-creation&data=05%7C01%7Calberto.muriel%40se.com%7C7738cb52bb6c457400cc08da6103a313%7C6e51e1adc54b4b39b5980ffe9ae68fef%7C0%7C0%7C637928965509926830%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=zQ9en4Tlc2UMiKhAfkfqPs%2FuR2aY42vrP6qmlA7jFdA%3D&reserved=0) (CLI) doesn’t cover our needs as we use nuget cli for .NET Framework projects.

Will be great to have any update regarding the verification as we are really interested as it’s a main requisite for our organization to be able use any GH Actions.
Seems there's more people as @bruno-garcia interested on the verification as well.

Regards,
Alberto M

**Comment by kenta2097** [comment]
Hi @jeffkl , 

We are happy to say that we are now able to start using your action.
This issue can be marked as Solved.

https://github.com/marketplace/actions/setup-nuget-exe-for-use-with-actions

Thanks for your efforts on the process.!

**Comment by nkolev92** [comment]
Closing as NuGet is now shown as a verified creator. 

![image](https://user-images.githubusercontent.com/2878341/192847381-723caa72-d077-4139-8525-48d43f8142ea.png)
